language: python

python:
    - "3.7"
env:
    - SECRET_KEY='TEST'

install:
    - pip install -r requirements.txt
scripts:
    - python manage.py test
    - coverage run --source='accounts' manage.py test && coverage report

after_success:
    - codecov
